//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Phrases {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonPhrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonPhrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Phrases.CommonPhrases", typeof(CommonPhrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AAA {
            get {
                return ResourceManager.GetString("AAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Caption_Error {
            get {
                return ResourceManager.GetString("Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Caption_Info {
            get {
                return ResourceManager.GetString("Caption_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Caption_Question {
            get {
                return ResourceManager.GetString("Caption_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Caption_Warning {
            get {
                return ResourceManager.GetString("Caption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output beyond the boundaries of the source array..
        /// </summary>
        public static string Exception_ArrayBoundsError {
            get {
                return ResourceManager.GetString("Exception_ArrayBoundsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration type mismatch. The flag is of type &quot;{0}&quot;, was expecting &quot;{1}&quot;..
        /// </summary>
        public static string Exception_EnumTypeMismatchInParam {
            get {
                return ResourceManager.GetString("Exception_EnumTypeMismatchInParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        public static string Exception_FileNotFound {
            get {
                return ResourceManager.GetString("Exception_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &quot;{0}&quot; contains an invalid character  &quot;{1}&quot;..
        /// </summary>
        public static string Exception_InvalidCharInParam {
            get {
                return ResourceManager.GetString("Exception_InvalidCharInParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid string representation of date and time..
        /// </summary>
        public static string Exception_InvalidDtRepresentation {
            get {
                return ResourceManager.GetString("Exception_InvalidDtRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Key Name..
        /// </summary>
        public static string Exception_InvalidKeyName {
            get {
                return ResourceManager.GetString("Exception_InvalidKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML node is null..
        /// </summary>
        public static string Exception_NodeIsNull {
            get {
                return ResourceManager.GetString("Exception_NodeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML node not found..
        /// </summary>
        public static string Exception_NodeNotFound {
            get {
                return ResourceManager.GetString("Exception_NodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML node type is not a string..
        /// </summary>
        public static string Exception_NodeTypeNotString {
            get {
                return ResourceManager.GetString("Exception_NodeTypeNotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument out of range..
        /// </summary>
        public static string Exception_ParamBoundsError {
            get {
                return ResourceManager.GetString("Exception_ParamBoundsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lower bound cannot be larger than the upper one..
        /// </summary>
        public static string Exception_ParamInvalidLowerBound_ {
            get {
                return ResourceManager.GetString("Exception_ParamInvalidLowerBound ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be nonnegative..
        /// </summary>
        public static string Exception_ParamIsNegative {
            get {
                return ResourceManager.GetString("Exception_ParamIsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; can&apos;t be converted to double..
        /// </summary>
        public static string Exception_ParamIsNotConvertToDouble {
            get {
                return ResourceManager.GetString("Exception_ParamIsNotConvertToDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; can&apos;t be converted to enumerable..
        /// </summary>
        public static string Exception_ParamIsNotConvertToEnum {
            get {
                return ResourceManager.GetString("Exception_ParamIsNotConvertToEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &quot;{0}&quot; of the argument &quot;{1}&quot; must be enumerable..
        /// </summary>
        public static string Exception_ParamIsNotEnum {
            get {
                return ResourceManager.GetString("Exception_ParamIsNotEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; is not hexadecimal..
        /// </summary>
        public static string Exception_ParamIsNotHex {
            get {
                return ResourceManager.GetString("Exception_ParamIsNotHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; is not a number..
        /// </summary>
        public static string Exception_ParamIsNotNumber {
            get {
                return ResourceManager.GetString("Exception_ParamIsNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be &lt; {1}..
        /// </summary>
        public static string Exception_ParamIsTooLong {
            get {
                return ResourceManager.GetString("Exception_ParamIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when changing the pointer position in the stream {0}..
        /// </summary>
        public static string Exception_SeekError {
            get {
                return ResourceManager.GetString("Exception_SeekError", resourceCulture);
            }
        }
    }
}
